from .sphinx_gallery_binder import alt_gen_binder_rst
from .sphinx_gallery_scrapers import alt_matplotlib_scraper
from sphinx_gallery import gen_rst

# modify single image arrangement
gen_rst.SINGLE_IMAGE = """
.. image:: /%s
    :class: sphx-glr-single-img
    :width: 80 %
    :align: center
"""
# remove the 'go to the end' part of the binder/download note
gen_rst.EXAMPLE_HEADER = """
.. DO NOT EDIT.
.. THIS FILE WAS AUTOMATICALLY GENERATED BY SPHINX-GALLERY.
.. TO MAKE CHANGES, EDIT THE SOURCE PYTHON FILE:
.. "{0}"
.. LINE NUMBERS ARE GIVEN BELOW.

.. only:: html

    .. note::
        :class: sphx-glr-download-link-note

.. rst-class:: sphx-glr-example-title

.. _sphx_glr_{1}:

"""
