name: DocsTest

on:
  push:
  pull_request:
    branches:
      - develop
      - feature/**
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  build:
    name: Build Docs
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            python-version: ${{ matrix.python-version }}
            enable-cache: true
            cache-dependency-glob: |
                **/pyproject.toml
      - name: Python Packages Install
        run: |
          uv sync --extra docs --extra skl
      - name: Build
        run: |
          cd docs && uv run make html
