name: Unittest

on:
  push:
  pull_request:
    branches:
      - develop
      - feature/**
  schedule:
    - cron: "0 0 * * 0" # weekly

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v6
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            python-version: ${{ matrix.python-version }}
            enable-cache: true
            cache-dependency-glob: |
                **/pyproject.toml
      - name: Python Packages Install
        run: |
          uv sync --extra dev
          uv pip install .
      - name: Test Windows
        if: runner.os == 'Windows'
        env:
          MPLBACKEND: Agg
        run: uv run pytest
      - name: Test MacOS
        if: runner.os == 'macOS'
        run: uv run pytest
      - name: Prep Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install jq curl  # codacy requirement
          sudo apt-get install xvfb
      - name: Test Linux
        if: runner.os == 'Linux'
        run: |
          xvfb-run uv run pytest
      - name: Coveralls
        env:
          COVERALLS_SERVICE_NAME: github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.test-name }}
          COVERALLS_PARALLEL: true
        run: |
          uv run coveralls
  coveralls:
    name: Indicate completion to coveralls.io
    needs: unit_tests
    if: success() || failure()
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          uv run coveralls --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
